### ISSUE TITLE
Calibrating and finding overshoot value times out waiting for heating system to start on v4

### ISSUE THREAD

**Issue by rouke-broersma** [Alexwijn/SAT#77]
On v3 I can configure SAT with automatic gains calculation, on v4 this times out after 10 minutes without ever having started anything it seems:

```
2025-01-06 21:45:37.911 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:45:44.305 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending! (<Task pending name='Task-25413' coro=<StatusManager._process_updates() done, defined at /usr/local/lib/python3.13/site-packages/pyotgw/status.py:106> wait_for=<Future cancelled>>)
2025-01-06 21:45:52.913 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:46:07.915 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:46:22.916 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:46:37.918 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:46:52.919 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:47:07.920 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:47:22.921 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:47:37.923 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:47:52.924 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:48:07.926 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:48:22.927 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:48:37.929 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:48:52.930 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:49:07.932 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:49:22.934 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:49:37.935 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:49:52.937 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:50:07.938 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:50:22.939 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for heating system to start
2025-01-06 21:50:37.913 WARNING (MainThread) [custom_components.sat.config_flow] Timed out during overshoot protection calculation.
```

Upgrading to v4 afterwards does work and I seem to be able to control the gateway without issues after initial setup and then upgrade.

I am using a nodo shop opentherm utp gateway connected to a Rehema Avanta c28 boiler and a Nest v3 OpenTherm thermostat. SAT is connected to the opentherm gateway through serial over tcp. Please let me know what I can do to troubleshoot this or if there are any other logs I can provide you with.

**Comment by sergeantd83** [comment]
Maybe we need to look again at the new OPV calibration process. Meanwhile you can test the manual OPV calculation method https://github.com/Alexwijn/SAT/discussions/36.

**Comment by rouke-broersma** [comment]
For reference, these are the logs on v3:

```
2025-01-06 21:57:23.211 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('serial.urlhandler',) in /usr/local/lib/python3.13/site-packages/serial/__init__.py, line 74: importlib.import_module(package_name) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/pyotgw/connection.py", line 115, in _attempt_connect
    transport, protocol = await serial_asyncio.create_serial_connection(
  File "/usr/local/lib/python3.13/site-packages/serial_asyncio/__init__.py", line 448, in create_serial_connection
    serial_instance = serial.serial_for_url(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/serial/__init__.py", line 74, in serial_for_url
    importlib.import_module(package_name)
2025-01-06 21:57:23.214 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('.protocol_socket', 'serial.urlhandler') in /usr/local/lib/python3.13/site-packages/serial/__init__.py, line 75: handler_module = importlib.import_module(module_name, package_name) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/pyotgw/connection.py", line 115, in _attempt_connect
    transport, protocol = await serial_asyncio.create_serial_connection(
  File "/usr/local/lib/python3.13/site-packages/serial_asyncio/__init__.py", line 448, in create_serial_connection
    serial_instance = serial.serial_for_url(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/serial/__init__.py", line 75, in serial_for_url
    handler_module = importlib.import_module(module_name, package_name)
2025-01-06 21:58:06.522 WARNING (MainThread) [homeassistant.data_entry_flow] custom_components.sat.config_flow::SatFlowHandler calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
2025-01-06 21:58:06.547 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:11.626 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:16.655 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:21.682 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:26.715 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:31.744 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:36.786 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:41.819 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:46.846 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:51.880 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:58:56.913 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:01.942 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:06.971 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:12.005 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:17.036 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:22.065 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:27.099 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:32.130 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:37.169 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:42.197 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:47.224 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:52.252 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 21:59:57.279 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 22:00:02.306 WARNING (MainThread) [custom_components.sat.overshoot_protection] Heating system is not running yet
2025-01-06 22:00:44.821 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'sat' calls `async_add_job`, which should be reviewed against https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/sat/__init__.py, line 37: await _hass.async_add_job(_hass.config_entries.async_forward_entry_setup(_entry, CLIMATE_DOMAIN)). This will stop working in Home Assistant 2025.4, please create a bug report at https://github.com/Alexwijn/SAT/issues
2025-01-06 22:00:44.825 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration, sat with title: Remeha Avanta c28 and entry_id: 01JGYPQ1552TQADRZJ35D5VMTH, which is deprecated, await async_forward_entry_setups instead. This will stop working in Home Assistant 2025.6, please report this issue
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2331, in async_forward_entry_setup
    report_usage(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 234, in report_usage
    _LOGGER.warning(msg, stack_info=True)
2025-01-06 22:00:44.850 WARNING (MainThread) [custom_components.sat.climate] No previously saved temperature, setting to 7
2025-01-06 22:00:45.017 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'sat' calls `async_add_job`, which should be reviewed against https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/sat/__init__.py, line 38: await _hass.async_add_job(_hass.config_entries.async_forward_entry_setups(_entry, [SENSOR_DOMAIN, NUMBER_DOMAIN, BINARY_SENSOR_DOMAIN])). This will stop working in Home Assistant 2025.4, please create a bug report at https://github.com/Alexwijn/SAT/issues
```

While this also logs a similar message for a while, it does after some minutes return with a calculation in the config low, allowing me to finish setup of the device.

**Comment by rouke-broersma** [comment]
> Maybe we need to look again at the new OPV calibration process. Meanwhile you can test the manual OPV calculation method #36.

On v3 I get a OPV of ~31c after about 3 minutes, should I not trust this value and rather calculate it myself?

**Comment by sergeantd83** [comment]
Yes, better not to trust this value. What’s your boiler brand?

**Comment by rouke-broersma** [comment]
> Yes, better not to trust this value. What’s your boiler brand?

Remeha Avanta

**Comment by MarkC1210** [comment]
Just started my journey with SAT, after realising this winter that the Ideal weather compensation system does not work if you plug in an opentherm thermostat over an on/off one, it becomes a glorified outdoor temp sensor and expects the thermostat to do all the work.

Anyway same problem for me Ideal Vouge Max C40, autotune doesn't finish and timesout and just sits there, so for not done a quick manual calc and got a value of 44 not idea if this is close :)

So on a separate subject what is the "Current Power" sensor? I've set the min/max gas and that is working but current power remains unknown

**Comment by sergeantd83** [comment]
Yes, this value looks fine.

**Comment by enricoschroeder** [comment]
I have the same issue using ESM-ESP and a Bosch Condens gas boiler. Any advice?

**Comment by sergeantd83** [comment]
It is a common issue we encounter ( especially with EMS-ESP ). This happens because it handles power ( modulation in the OpenTherm world ) differently than OpenTherm. I would suggest using the boiler flow water temperature value as the Overshoot Protection value—the one that keeps your boiler at the lowest power while the boiler is running.

**Comment by rouke-broersma** [comment]
@sergeantd83 are you sure this is fixed?

**Comment by sergeantd83** [comment]
Correct, this not fixed. We need to take a better look about how we will improve the calculation process. Sorry for the hassle.

**Comment by stijnfrishert** [comment]
Running into this as well, using a Nobo with a Wemos D1 Mini.

First time I'm setting this up, so I have no idea what to fill in manually. Is [this](https://github.com/Alexwijn/SAT/discussions/36) still relevant?

---

Well, I just closed the window, and when I press "Add" again on the integration it says it completed succesfully with the following OPV:

<img width="615" height="578" alt="Image" src="https://github.com/user-attachments/assets/62db8f29-314c-40a8-80ea-b403442f37be" />

If that seems correct, the issue's more that the calibration window doesn't close? Did see a timeout in the log:

```
2026-01-27 10:41:03.330 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending! (task: <Task pending name='Task-1864' coro=<StatusManager._process_updates() done, defined at /usr/local/lib/python3.13/site-packages/pyotgw/status.py:106> wait_for=<Future cancelled>>)
2026-01-27 10:41:18.379 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for a stable temperature
2026-01-27 10:41:33.538 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for a stable temperature
2026-01-27 10:41:48.689 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for a stable temperature
2026-01-27 10:42:03.859 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for a stable temperature
2026-01-27 10:42:19.009 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for a stable temperature
2026-01-27 10:42:34.168 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for a stable temperature
2026-01-27 10:42:49.308 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for a stable temperature
2026-01-27 10:43:04.489 WARNING (MainThread) [custom_components.sat.overshoot_protection] Waiting for a stable temperature
```

I closed the dialog at 10:53.

**Comment by rouke-broersma** [comment]
@stijnfrishert calibration seems to work fine for you. At the bottom of the dialog are two buttons, you need to choose continue with current calibration.

**Comment by stijnfrishert** [comment]
Ah no, the way I screenshotted this is maybe a bit confusing, @rouke-broersma.

I had the calibration run, and after 40 minutes it was still spinning. I then manually closed the calibration by pressing X.

When I then pressed Add again on the integration, that screenshotted window popped up showing the calibration ended successfully.

In other words, the issue for me isn't that the calib isn't working, it's that the progress window doesn't get a signal that the calibration has finished and doesn't let the user know—or is that just how it was designed, and users are expected to close it after 20 minutes themselves?.

**Comment by renatoriccio** [comment]
@sergeantd83 I have the same issue with EMS-ESP. When you say "I would suggest using the boiler flow water temperature value as the Overshoot Protection value" Do you refer to "Current Flow Temperature"?

<img width="582" height="519" alt="Image" src="https://github.com/user-attachments/assets/bedd15be-a59f-422b-b65b-7cb572b6889a" />
